// SPDX-License-Identifier: MPL-2.0
const context=document.querySelector('#context'),capture=document.querySelector('#capture'),substitution=document.querySelector('#substitution'),result=document.querySelector('#result'),evidence=document.querySelector('#evidence'),run=document.querySelector('#run'),toggle=document.querySelector('#toggle'),source=document.querySelector('#source'),settings=document.querySelector('#settings'),status=document.querySelector('#status');
const extensionVersion=document.querySelector('#extension-version');
let activeOrigin=null,activeRule=null,stored=null;
async function render(){const manifest=browser.runtime.getManifest();extensionVersion.textContent=`v${manifest.version}`;const [tab]=await browser.tabs.query({active:true,currentWindow:true});stored=await browser.storage.local.get(['instanceUrl','sites','siteDiagnostics']);try{activeOrigin=new URL(tab.url).origin}catch{activeOrigin=null}activeRule=(stored.sites||[]).find(site=>site.origin===activeOrigin);context.textContent=activeOrigin||'This page has no eligible HTTPS origin';capture.textContent=activeRule?(activeRule.capture?'Active':'Paused'):'Not enabled';substitution.textContent=activeRule?(activeRule.substitution?'Active':'Paused'):'Not enabled';toggle.textContent=activeRule?.substitution?'Pause substitution':'Resume substitution';const diagnostic=stored.siteDiagnostics?.[activeOrigin];result.textContent=diagnostic?`${diagnostic.state}. ${diagnostic.reason}.`:'No cache attempt recorded';const labels=[];if(diagnostic?.previouslyObserved)labels.push('◉ Previously observed');if(diagnostic?.storedInObjectStore)labels.push('✓ Stored in ObjectStore');evidence.textContent=labels.join(' · ')||'No observation or ObjectStore evidence recorded';evidence.title='Status framing only; stored media bytes are never watermarked or changed.';for(const button of [run,toggle,source])button.disabled=!activeRule;}
run.onclick=async()=>{status.textContent='Checking visible media…';await browser.runtime.sendMessage({command:'run-cache'});status.textContent='Cache check completed. Origin media remains available on every failure.';await render();};
toggle.onclick=async()=>{if(!activeRule)return;activeRule.substitution=!activeRule.substitution;await browser.storage.local.set({sites:stored.sites});status.textContent=activeRule.substitution?'Substitution resumed for this site.':'Substitution paused; this site remains origin-served.';await render();};
source.onclick=async()=>{if(!stored.instanceUrl||!activeOrigin)return;const url=new URL('/products/pinakotheke/app/',stored.instanceUrl);url.searchParams.set('source','websites');url.searchParams.set('origin',activeOrigin);await browser.tabs.create({url:url.href});};
settings.onclick=()=>browser.runtime.openOptionsPage();
render();
