// SPDX-License-Identifier: MPL-2.0
const context=document.querySelector('#context'),capture=document.querySelector('#capture'),substitution=document.querySelector('#substitution'),captureResult=document.querySelector('#capture-result'),substitutionResult=document.querySelector('#substitution-result'),evidence=document.querySelector('#evidence'),run=document.querySelector('#run'),toggle=document.querySelector('#toggle'),source=document.querySelector('#source'),settings=document.querySelector('#settings'),status=document.querySelector('#status');
const extensionVersion=document.querySelector('#extension-version');
const diagnosticLog=document.querySelector('#diagnostic-log'),downloadDiagnostics=document.querySelector('#download-diagnostics');
const videoDownloads=document.querySelector('#video-downloads');
const X_MEDIA_PERMISSION='https://video.twimg.com/*';
let activeOrigin=null,activeRule=null,stored=null,xMediaPermissionMissing=false;
async function needsXMediaPermission(){return activeOrigin==='https://x.com'&&activeRule?.capture&&activeRule.xIngress&&activeRule.media.includes('videos')&&!await browser.permissions.contains({origins:[X_MEDIA_PERMISSION]});}
async function render(){const manifest=browser.runtime.getManifest();extensionVersion.textContent=`v${manifest.version}`;const [tab]=await browser.tabs.query({active:true,currentWindow:true});stored=await browser.storage.local.get(['instanceUrl','sites','siteDiagnostics','diagnosticEvents']);try{activeOrigin=new URL(tab.url).origin}catch{activeOrigin=null}activeRule=(stored.sites||[]).find(site=>site.origin===activeOrigin);context.textContent=activeOrigin||'This page has no eligible HTTPS origin';capture.textContent=activeRule?(activeRule.capture?'Active':'Paused'):'Not enabled';substitution.textContent=activeRule?(activeRule.substitution?'Active':'Paused'):'Not enabled';toggle.textContent=activeRule?.substitution?'Pause substitution':'Resume substitution';const diagnostic=stored.siteDiagnostics?.[activeOrigin];xMediaPermissionMissing=await needsXMediaPermission();captureResult.textContent=xMediaPermissionMissing?'Permission required. Click Run cache for visible media and approve access to X media.':diagnostic?.captureState?`${diagnostic.captureState}. ${diagnostic.captureReason}.`:'No capture attempt recorded';substitutionResult.textContent=diagnostic?.substitutionState?`${diagnostic.substitutionState}. ${diagnostic.substitutionReason}.`:'No substitution attempt recorded';const labels=[];if(diagnostic?.previouslyObserved)labels.push('◉ Previously observed');if(diagnostic?.storedInObjectStore)labels.push('✓ Stored in ObjectStore');evidence.textContent=labels.join(' · ')||'No observation or ObjectStore evidence recorded';evidence.title='Status framing only; stored media bytes are never watermarked or changed.';const events=Array.isArray(stored.diagnosticEvents)?stored.diagnosticEvents:[];diagnosticLog.textContent=events.slice(-12).map(event=>`${event.at} ${event.stage} ${event.outcome} ${event.origin||'-'} ${event.detail}`).join('\n')||'No diagnostic events recorded';for(const button of [run,toggle,source])button.disabled=!activeRule;}
run.onclick=()=>{if(xMediaPermissionMissing){status.textContent='Requesting access to X video media…';browser.permissions.request({origins:[X_MEDIA_PERMISSION]}).then(async granted=>{if(!granted){status.textContent='X video capture remains disabled because media permission was not granted.';await render();return;}status.textContent='X video access enabled. Reload the X page, then play the video again.';await render();});return;}status.textContent='Checking visible media…';browser.runtime.sendMessage({command:'run-cache'}).then(async()=>{status.textContent='Cache check completed. Origin media remains available on every failure.';await render();});};
toggle.onclick=async()=>{if(!activeRule)return;activeRule.substitution=!activeRule.substitution;await browser.storage.local.set({sites:stored.sites});status.textContent=activeRule.substitution?'Substitution resumed for this site.':'Substitution paused; this site remains origin-served.';await render();};
source.onclick=async()=>{if(!stored.instanceUrl||!activeOrigin)return;const url=new URL('/products/pinakotheke/app/',stored.instanceUrl);url.searchParams.set('source','websites');url.searchParams.set('origin',activeOrigin);await browser.tabs.create({url:url.href});};
settings.onclick=()=>browser.runtime.openOptionsPage();
downloadDiagnostics.onclick=async()=>{const data=await browser.storage.local.get(['diagnosticEvents']);const blob=new Blob([JSON.stringify({schema_version:'pinakotheke.extension-diagnostics.v1',version:browser.runtime.getManifest().version,events:data.diagnosticEvents||[]},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`pinakotheke-extension-diagnostics-${Date.now()}.json`;link.click();URL.revokeObjectURL(url);};
async function renderVideoCaptures(){await browser.runtime.sendMessage({command:'refresh-media-captures'});const data=await browser.storage.local.get(['mediaCaptureStates']);const entries=(Array.isArray(data.mediaCaptureStates)?data.mediaCaptureStates:[]).filter(entry=>!activeOrigin||entry.origin===activeOrigin).slice(-8).reverse();videoDownloads.replaceChildren(...(entries.length?entries.map(entry=>{const item=document.createElement('li');const when=new Date(entry.updatedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});item.textContent=`${entry.kind} ${entry.planId.slice(0,12)} — ${entry.state}. ${entry.detail} (${when})`;return item;}):[Object.assign(document.createElement('li'),{textContent:'No images or videos selected in this browser session.'})]));}
browser.storage.onChanged.addListener(changes=>{if(changes.mediaCaptureStates)void renderVideoCaptures();});
render().then(renderVideoCaptures);
